Update config new

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,11 +42,7 @@ commands:
           when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS=$(curl \
-              -H "Content-Type: text/plain" \
-              -H "Authorization:$LUCID_JWT_TOKEN" \
-              --request GET \
-              -k --data "1" ${KEY_VALUE_STORE_ENDPOINT}/migration_${CIRCLE_WORKFLOW_ID:0:7})
+            SUCCESS=$(curl --insecure  https://kvdb.io/7YEQYqnSBWr3e9zmRvyggp/migration_${CIRCLE_WORKFLOW_ID:0:7})
             if(( $SUCCESS==1 )); 
             then
               #  Add revert code here. You can find this in the Getting Started section.
@@ -400,14 +396,14 @@ jobs:
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
       # Here's where you will add some code to rollback on failure  
-      # - revert-migrations
-      # - install-awscli
-      # - destroy-environment:
-      #     description: backend
-      #     stack-name: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
-      # - destroy-environment:
-      #     description: frontend
-      #     stack-name: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations
+      - install-awscli
+      - destroy-environment:
+          description: backend
+          stack-name: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          description: frontend
+          stack-name: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
 
   smoke-test:
     docker:
@@ -449,7 +445,7 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
               # Change this to 0 after the job fails
-              exit 0
+              exit 1
             else
               exit 1
             fi
@@ -461,6 +457,28 @@ jobs:
       - destroy-environment:
           description: frontend
           stack-name: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+
+  cloudfront-update:
+    docker:
+      - image: "amazon/aws-cli:latest"
+    steps:
+      - checkout
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name InitialStack \
+            --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --tags project=udapeople
+      # Here's where you will add some code to rollback on failure  
+      - revert-migrations
+      - destroy-environment:
+          description: backend
+          stack-name: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          description: frontend
+          stack-name: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" 
 
 workflows:
   default:
@@ -490,3 +508,5 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
